[package]
authors = ["Vinzent Steinberg <Vinzent.Steinberg@gmail.com>"]
description = "Xoroshiro128+, xorshift1024*Ï† and splitmix64 random number generators"
keywords = ["rng"]
categories = ["algorithms"]
license = "MIT/Apache-2.0"
name = "xoroshiro"
repository = "https://github.com/vks/xoroshiro"
documentation = "https://docs.rs/xoroshiro"
version = "0.1.0"

[dependencies]
byteorder = "1"
rand = "0.3"
aesni = { version = "0.1", optional = true }

[dev-dependencies]
bencher = "0.1"

[features]
default = []
unstable = ["aesni"]

[[bench]]
name = "bench"
harness = false
